### ISSUE TITLE
Comentarios entrega #1

### ISSUE THREAD

**Issue by edjus** [TomBPotochek/algochess#2]
Buenas aquí les dejo algunos comentarios y observaciones sobre la entrega 1:
- [x] Agregar un README con la siguiente información: Nombre del grupo, integrantes del grupo, enlace al informe y diagramas actualizados. Además un enlace que muestre el estado de *Travis*.

-  [x] Servidor de integración continua en estado **failed**, revisen por que es ésto y traten de arreglarlo, la idea es tener siempre el servidor de CI en **successful**.

- [x] Reordenar y agrupar clases, no tener todas las clases sueltas, tanto para el modelo como para test. Tratar de agruparlos en paquetes que tengan relación, manteniendo la cohesión.

- [x] Números mágicos: Hay varias números sueltos por ahí (vida inicial, daño, costo, etc) reemplazarlos, existen dos posibilidades:
- Constantes dentro de la clase:
```
   private final int DANIO = 10;
   public ArmaSoldado() {
        super(DANIO, Rango.cercano());
    }
```
- Tener una clase estática, con todos las constantes juntas:
```
public static class ProveedorConstantes(){
   public static int DANIO_ARMA_SOLADO = 10;
   public static int DANIO_ARMA_JINETE = 10;
   public static int VIDA_SOLDADO = 100;
   ...
}
```
De la segunda manera es más sencillo configurar las constantes del juego y permite probar algunas funcionalidades del juego de manera más rápida durante las correcciones.

- [x] Test que no hacen nada o están comentados por ejemplo: `CasillaTest`, `CatapultaTest`, etc. Revisarlos y borrarlos si no hacen falta.

- [x] Faltan más test unitarios, `Casilla` por ejemplo, si bien está bien tener pruebas de *integración* , también debe haber pruebas unitarias.

- [x] Hay codigo comentado en la clase `Jinete`, analicen si se tiene que quitar y busquen por otro casos parecidos.

- [x] El método `atacar(Unidad unaUnidad, Tablero tablero)`, se repite exactamente igual en todas las unidades, extraerlo en una entidad/abstracción. Se me ocurre,  por como está su código ahora, crear la interfaz `Movible` que defina los métodos propios asociados al movimiento, luego crear una clase Abstracta para cada posible unidad (que se mueva, que ataque, que se mueva y ataque) y que cada unidad extienda la que necesita. Es aplicar uno de los Principios SOLID, la pregunta es: qué principio es?.

- [x] `Equipo` debería ser una clase y no un `String`, de esta manera se le puede agregar comportamiento, dado que cada unidad, jugador, casillero tiene un equipo asociado. 

- [x] El mensaje 'moverUnidad(Posicion posicionOrigen, Posicion posicionDestino)` en tablero no es del todo correcto, dado que si lo quieren hacer así debería recibir la `Unidad` y la posición de destino, y dentro mandarle el mensaje a unidad de moverse y que se resuelva por delegación el *vaciar* y *ocupar* casilla.
```
    public void moverUnidad(Unidad unaUnidad, Posicion posicionDestino) {
         //validar que es una posición válida
    	Casilla casillaDestino = this.tablero.get(posicionDestino);
        unaUnidad.mover(casillaDestino); //internamente se resuelve el ocupado y vaciado de las casillas.
    }
```
Otra manera de hacerlo sería directamente mandar el mensaje a unidad:`unaUnidad.mover(posicionDestino, tablero)`, sería una variante del anterior. Luego hay otra posibilidad `unaUnidad.mover(tablero)` en éste caso la unidad ya tiene una dirección fijada y sabe a donde se debe mover solo necesita al tablero para actualizar las casillas.

Por el momento es solo eso.

Cualquier duda me escriben.

**Comment by edjus** [comment]
Buenas, como quedó el estado de los dos items que faltan? Además la tarea del README está incompleta, falta el enlace al informe y a los diagramas.

**Comment by TomBPotochek** [comment]
@edjus respecto a lo de atacar, lo estabamos haciendo de esa manera pero no nos gusta como esta quedando. Ahora estabamos por pasar a hacerlo por composicion en vez de crear clases abstractas que hereden, porque sino de todos modos queda repetido el codigo de atacar en atacante y atacanteMovible.

respecto al de moverUnidad de tablero, la forma en la que ya estaba hecha era que uno llama al mover de unidad `unidad.mover(posicionDestino. tablero)` quien luego usa tablero para llamar a moverUnidad con la posicion destino y la posicion propia de la unidad. No es eso a lo que te referias con esto?: 
> Otra manera de hacerlo sería directamente mandar el mensaje a unidad:unaUnidad.mover(posicionDestino, tablero), sería una variante del anterior.

**Comment by edjus** [comment]
- Me parece bien el enfoque que van a tomar.
- No llego a entender a lo que te refieres, pero la idea es que no se haga algo como: ```tablero.mover(posiciónOrigen, posiciónDestino)```
Si no se use a la unidad, que ya contiene su posición (posiciónOrigen). Si no se entiende del todo lo vemos mañana en la segunda entrega.
